server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/testDB2"
    name: "testDB2"
    username: "userDB2"
    password: "userDB2"
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop


